include(ExternalProject)

set(LCMS2_STATIC_LIBRARY
    "${THIRD_PARTY_LIB_PATH}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}lcms2${CMAKE_STATIC_LIBRARY_SUFFIX}")

ExternalProject_Add(ep_lcms2
    GIT_REPOSITORY https://github.com/mm2/Little-CMS
    GIT_TAG lcms2.19.1
    BUILD_BYPRODUCTS ${LCMS2_STATIC_LIBRARY}
    CMAKE_ARGS
        ${EP_CMAKE_ARGS}
        -DLCMS2_BUILD_SHARED=OFF
        -DLCMS2_BUILD_STATIC=ON
        -DLCMS2_BUILD_TOOLS=OFF
        -DLCMS2_BUILD_TESTS=OFF
        -DLCMS2_BUILD_JPGICC=OFF
        -DLCMS2_BUILD_TIFICC=OFF
        -DLCMS2_BUILD_TIFDIFF=OFF
        -DLCMS2_WITH_JPEG=OFF
        -DLCMS2_WITH_TIFF=OFF
        -DLCMS2_WITH_ZLIB=OFF
        -DLCMS2_WITH_FASTFLOAT=OFF
)
